spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecommerce_catalog}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8087/realms/ecommerce}

ecommerce:
  security:
    permit-all:
      - "GET:/api/v1/products/**"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${SERVER_PORT:8081}
